import{a as b,S}from"./assets/vendor-DBMDmZZa.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const v="47849639-14a05baa764e681cfc3185886",w="https://pixabay.com/api/";async function g(t,r=1,a=15){try{return(await b.get(w,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a}})).data}catch(s){throw console.error("Error fetching images:",s),s}}function m(t){return t.map(({webformatURL:r,largeImageURL:a,tags:s,likes:e,views:o,comments:n,downloads:L})=>`
        <a class="gallery-item" href="${a}">
          <div class="gallery__card">
            <img class="gallery__image" src="${r}" alt="${s}" loading="lazy" />
            <div class="gallery__info">
              <p><b>Likes:</b> ${e}</p>
              <p><b>Views:</b> ${o}</p>
              <p><b>Comments:</b> ${n}</p>
              <p><b>Downloads:</b> ${L}</p>
            </div>
          </div>
        </a>`).join("")}function i(t){const r=document.querySelector(".error-message");r.textContent=t,r.classList.remove("hidden")}function y(){document.querySelector(".error-message").classList.add("hidden")}const q=document.querySelector("#search-form"),h=document.querySelector(".gallery"),d=document.querySelector(".load-more"),u=document.querySelector(".loader");let l="",c=1;const f=15;let p=new S(".gallery a");q.addEventListener("submit",M);d.addEventListener("click",_);async function M(t){if(t.preventDefault(),l=t.target.elements.searchQuery.value.trim(),c=1,h.innerHTML="",y(),d.classList.add("hidden"),!l){i("Please enter a search query.");return}try{u.classList.remove("hidden");const r=await g(l,c,f);if(u.classList.add("hidden"),r.hits.length===0){i("Sorry, no images found. Try a different query!");return}h.innerHTML=m(r.hits),p.refresh(),d.classList.toggle("hidden",r.hits.length<f)}catch(r){i("Something went wrong. Please try again later."),console.error(r)}}async function _(){c+=1,y();try{u.classList.remove("hidden");const t=await g(l,c,f);u.classList.add("hidden"),h.insertAdjacentHTML("beforeend",m(t.hits)),p.refresh(),c*f>=t.totalHits&&(d.classList.add("hidden"),i("We're sorry, but you've reached the end of search results."))}catch(t){i("Something went wrong. Please try again later."),console.error(t)}}
//# sourceMappingURL=index.js.map
